### ISSUE TITLE
SSA pass can produce phi nodes with tuples as conditions

### ISSUE THREAD

**Issue by rdaly525** [leonardt/ast_tools#30]
Applying SSA to foo
```
def foo(a : Bit) -> (Bit, Bit):
    if a:
        return a, Bit(0)
    else:
        return ~a, Bit(1)
```
Results in the following
```
def foo(a : Bit) ->(Bit,Bit):
    __return_value0 = a, Bit(0)
    __return_value1 = ~a, Bit(1)
    return __phi(a, __return_value0, __return_value1)
```
This is an issue when __phi is SMTBit.ite since it does not support tuples as arguments. 

One of the following should occur:
1) Dissallow this style of code (returning multiple values within a branch)
2) Updating SMT.ite to handle tuples appropriately
3) Update SSA to split this code into multiple phi nodes

@cdonovick, thoughts?

**Comment by cdonovick** [comment]
4. write a separate pass that splits tuple assignment into multiple variables.

I will implement

**Comment by cdonovick** [comment]
@rdaly525 
My idea actually turns out to be pretty hard to implement in a robust way.  

2. is possible.  However,this not just an issue for SMT it also an issue for straight py Bit which also does not support tuple arguments.

3. Doesn't fix the generalized version of this problem

```Python
def foo(cond):
    if cond:
        x = 0, 0
    else:
        x = 1, 1
    return x
```

My current suggestion would be to support tuple ites in Bit (i.e. option 2) however could you confirm that this works in magma?

**Comment by rdaly525** [comment]
Okay, lets do option 2. Magma does handle this somehow since there is code like this in Lassen

**Comment by cdonovick** [comment]
Resolved via https://github.com/leonardt/hwtypes/pull/115
